version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    ports:
      - 8800:8080
      - 50000:50000
    networks:
      - devops-network
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  
  db-sonar:
    container_name: db-sonar
    image: postgres:latest
    ports:
      - "8900:5432"
    networks:
      - devops-network
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  sonar:
    container_name: sonar
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - devops-network
    depends_on:
      - db-sonar
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db-sonar:5432/sonar
      - SONAR_JDBC_USERNAME=postgres
      - SONAR_JDBC_PASSWORD=root
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
   
networks:
  devops-network:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data: